version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8099:80"
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
#        build: docker/php-fpm
        image: php:8.1-fpm
        volumes:
            - .:/var/www/html
        links:
            - postgres
        env_file: .env

    postgres:
        image: postgres:16-alpine
#        volumes:
#            - ~/apps/postgres:/var/lib/postgresql/data
        env_file: .env
